fn main() {
  let x = 5;

  println!("number is {}", x);

  x = 8;  /// has error
  println!("number is {}", x);
}
